sudo: required
language: java
jdk: oraclejdk8
services:
  - docker
script:
  - docker build -t umasuo/data-processor .


after_success:
  - docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD";
    docker push umasuo/data-processor;